swagger-api:
  version: "1.0"

spring:
#  data:
#    mongodb:
#      url: mongodb://localhost:27017/db

#  jpa:
#    hibernate:
#      ddl-auto: update
#      use-new-id-generator-mappings: false
#    show-sql: true
#    properties:
#      hibernate:
#        generate_statistics: true
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQL81Dialect
#  datasource:
#    url: jdbc:postgresql://${PSQL_DATASOURCE_URL:localhost:5432/PoLabs}
#    username: ${PSQL_DATASOURCE_USERNAME:postgres}
#    password: ${PSQL_DATASOURCE_PASSWORD:postgre}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8091
  servlet:
    context-path: /po